CREATE TABLE [staging].[population_typed] (
    [FileName]      NVARCHAR (100) NULL,
    [SourceItemId]  NVARCHAR (100) CONSTRAINT [DF_population_typed_SourceItemId] DEFAULT (N'-1') NULL,
    [CountryName]   NVARCHAR (100) NULL,
    [CountryCode]   NVARCHAR (100) NULL,
    [IndicatorName] NVARCHAR (100) NULL,
    [IndicatorCode] NVARCHAR (100) NULL,
    [1960]          BIGINT         NULL,
    [1961]          BIGINT         NULL,
    [1962]          BIGINT         NULL,
    [1963]          BIGINT         NULL,
    [1964]          BIGINT         NULL,
    [1965]          BIGINT         NULL,
    [1966]          BIGINT         NULL,
    [1967]          BIGINT         NULL,
    [1968]          BIGINT         NULL,
    [1969]          BIGINT         NULL,
    [1970]          BIGINT         NULL,
    [1971]          BIGINT         NULL,
    [1972]          BIGINT         NULL,
    [1973]          BIGINT         NULL,
    [1974]          BIGINT         NULL,
    [1975]          BIGINT         NULL,
    [1976]          BIGINT         NULL,
    [1977]          BIGINT         NULL,
    [1978]          BIGINT         NULL,
    [1979]          BIGINT         NULL,
    [1980]          BIGINT         NULL,
    [1981]          BIGINT         NULL,
    [1982]          BIGINT         NULL,
    [1983]          BIGINT         NULL,
    [1984]          BIGINT         NULL,
    [1985]          BIGINT         NULL,
    [1986]          BIGINT         NULL,
    [1987]          BIGINT         NULL,
    [1988]          BIGINT         NULL,
    [1989]          BIGINT         NULL,
    [1990]          BIGINT         NULL,
    [1991]          BIGINT         NULL,
    [1992]          BIGINT         NULL,
    [1993]          BIGINT         NULL,
    [1994]          BIGINT         NULL,
    [1995]          BIGINT         NULL,
    [1996]          BIGINT         NULL,
    [1997]          BIGINT         NULL,
    [1998]          BIGINT         NULL,
    [1999]          BIGINT         NULL,
    [2000]          BIGINT         NULL,
    [2001]          BIGINT         NULL,
    [2002]          BIGINT         NULL,
    [2003]          BIGINT         NULL,
    [2004]          BIGINT         NULL,
    [2005]          BIGINT         NULL,
    [2006]          BIGINT         NULL,
    [2007]          BIGINT         NULL,
    [2008]          BIGINT         NULL,
    [2009]          BIGINT         NULL,
    [2010]          BIGINT         NULL,
    [2011]          BIGINT         NULL,
    [2012]          BIGINT         NULL,
    [2013]          BIGINT         NULL,
    [2014]          BIGINT         NULL,
    [2015]          BIGINT         NULL,
    [2016]          BIGINT         NULL,
    [2017]          BIGINT         NULL,
    [2018]          BIGINT         NULL,
    [2019]          BIGINT         NULL,
    [sysCreatedAt]  DATETIME       CONSTRAINT [DF_population_typed_sysCreatedAt] DEFAULT (getutcdate()) NULL,
    [sysChangedAt]  DATETIME       CONSTRAINT [DF_population_typed_sysChangedAt] DEFAULT (getutcdate()) NULL,
    [sysCreatedBy]  INT            CONSTRAINT [DF_population_typed_sysCreatedBy] DEFAULT ((-1)) NOT NULL,
    [sysChangedBy]  INT            CONSTRAINT [DF_population_typed_sysChangedBy] DEFAULT ((-1)) NOT NULL
);

